let Players = [

    {
        "id": 0,
        "playerName": "Rinku Singh",
        "photo": 'https://bcciplayerimages.s3.ap-south-1.amazonaws.com/ipl/IPLHeadshot2023/152.png',
        "from": "KKR",
        "price": "1 Cr",
        "isPlaying": true,
        "description": "Batsman",
        "runs": "725",
        "wickets": "0",
    },
    {
        "id": 1,
        "playerName": "Andre Russell",
        "photo": 'https://bcciplayerimages.s3.ap-south-1.amazonaws.com/ipl/IPLHeadshot2023/141.png',
        "from": "KKR",
        "price": "5 Cr",
        "isPlaying": true,
        "description": "All Rounder",
        "runs": "2262",
        "wickets": "96",
    },
    {
        "id": 2,
        "playerName": "Lockie Ferguson",
        "photo": 'https://bcciplayerimages.s3.ap-south-1.amazonaws.com/ipl/IPLHeadshot2023/69.png',
        "from": "KKR",
        "price": "3 Cr",
        "isPlaying": true,
        "description": "Bowler",
        "runs": "67",
        "wickets": "37",
    },
    {
        "id": 3,
        "playerName": "Rohit Sharma",
        "photo": 'https://bcciplayerimages.s3.ap-south-1.amazonaws.com/ipl/IPLHeadshot2023/6.png',
        "from": "MI",
        "price": "7 Cr",
        "isPlaying": true,
        "description": "Batsman",
        "runs": "6211",
        "wickets": "0",
    },
    {
        "id": 4,
        "playerName": "Jofra Archer",
        "photo": 'https://bcciplayerimages.s3.ap-south-1.amazonaws.com/ipl/IPLHeadshot2023/181.png',
        "from": "MI",
        "price": "2.5 Cr",
        "isPlaying": true,
        "description": "All Rounder",
        "runs": "199",
        "wickets": "48",
    },
    {
        "id": 5,
        "playerName": "Piyush Chawla",
        "photo": 'https://bcciplayerimages.s3.ap-south-1.amazonaws.com/ipl/IPLHeadshot2023/149.png',
        "from": "MI",
        "price": "1.5 Cr",
        "isPlaying": true,
        "description": "Bolwer",
        "runs": "609",
        "wickets": "179",
    },
    {
        "id": 6,
        "playerName": "MS Dhoni",
        "photo": 'https://bcciplayerimages.s3.ap-south-1.amazonaws.com/ipl/IPLHeadshot2023/57.png',
        "from": "CSK",
        "price": "10 Cr",
        "isPlaying": true,
        "description": "Wicket Keeper Batsman",
        "runs": "500",
        "wickets": "0",
    },
    {
        "id": 7,
        "playerName": "Ruturaj Gaikwad",
        "photo": 'https://bcciplayerimages.s3.ap-south-1.amazonaws.com/ipl/IPLHeadshot2023/102.png',
        "from": "CSK",
        "price": "9 Cr",
        "isPlaying": true,
        "description": "Batsman",
        "runs": "300",
        "wickets": "0",
    },
    {
        "id": 8,
        "playerName": "Ben Stokes",
        "photo": 'https://bcciplayerimages.s3.ap-south-1.amazonaws.com/ipl/IPLHeadshot2023/177.png',
        "from": "CSK",
        "price": "8 Cr",
        "isPlaying": true,
        "description": "All-Rounder",
        "runs": "357",
        "wickets": "16",
    },
    {
        "id": 9,
        "playerName": "Virat Kohli",
        "photo": 'https://bcciplayerimages.s3.ap-south-1.amazonaws.com/ipl/IPLHeadshot2023/2.png',
        "from": "RCB",
        "price": "9.5 Cr",
        "isPlaying": true,
        "description": "Batsman",
        "runs": "915",
        "wickets": "0",
    },
    {
        "id": 10,
        "playerName": "David Willey",
        "photo": 'https://bcciplayerimages.s3.ap-south-1.amazonaws.com/ipl/IPLHeadshot2023/90.png',
        "from": "RCB",
        "price": "8.5 Cr",
        "isPlaying": true,
        "description": "All Rounder",
        "runs": "560",
        "wickets": "20",
    },
    {
        "id": 11,
        "playerName": "Mohammed Siraj",
        "photo": 'https://bcciplayerimages.s3.ap-south-1.amazonaws.com/ipl/IPLHeadshot2023/63.png',
        "from": "RCB",
        "price": "7.5 Cr",
        "isPlaying": true,
        "description": "Bowler",
        "runs": "58",
        "wickets": "50",
    },
    
    {
        "id": 12,
        "playerName": "Rilee Rossouw",
        "photo": 'https://bcciplayerimages.s3.ap-south-1.amazonaws.com/ipl/IPLHeadshot2023/1426.png',
        "from": "DC",
        "price": "10 Cr",
        "isPlaying": true,
        "description": "Batsman",
        "runs": "340",
        "wickets": "0",
    },
    {
        "id": 13,
        "playerName": "Kuldeep Yadav",
        "photo": 'https://bcciplayerimages.s3.ap-south-1.amazonaws.com/ipl/IPLHeadshot2023/14.png',
        "from": "DC",
        "price": "6.5 Cr",
        "isPlaying": true,
        "description": "Bowler",
        "runs": "100",
        "wickets": "30",
    },
    {
        "id": 14,
        "playerName": "Lungi Ngidi",
        "photo": 'https://bcciplayerimages.s3.ap-south-1.amazonaws.com/ipl/IPLHeadshot2023/99.png',
        "from": "DC",
        "price": "3.5 Cr",
        "isPlaying": true,
        "description": "Bowler",
        "runs": "150",
        "wickets": "50",
    },
    {
        "id": 15,
        "playerName": "Liam Livingstone",
        "photo": 'https://bcciplayerimages.s3.ap-south-1.amazonaws.com/ipl/IPLHeadshot2023/183.png',
        "from": "KXIP",
        "price": "6.5 Cr",
        "isPlaying": true,
        "description": "Batsman",
        "runs": "828",
        "wickets": "8",
    },
    {
        "id": 16,
        "playerName": "Sam Curran",
        "photo": 'https://bcciplayerimages.s3.ap-south-1.amazonaws.com/ipl/IPLHeadshot2023/138.png',
        "from": "KXIP",
        "price": "5 Cr",
        "isPlaying": true,
        "description": "All Rounder",
        "runs": "613",
        "wickets": "42",
    },
    {
        "id": 17,
        "playerName": "Kagiso Rabada",
        "photo": 'https://bcciplayerimages.s3.ap-south-1.amazonaws.com/ipl/IPLHeadshot2023/116.png',
        "from": "KXIP",
        "price": "3 Cr",
        "isPlaying": true,
        "description": "Bowler",
        "runs": "186",
        "wickets": "106",
    },
]